language: python
python:
- 3.6
before_install:
- pip install poetry flake8 pytest pytest-cov
install:
- poetry install
script:
- poetry run flake8
- poetry run pytest tests/ --cov=./
after_success:
- bash <(curl -s https://codecov.io/bash)
